import {
  UserProfile,
  Farmer,
  Crop,
  FarmerStock,
  Vendor,
  ProcurementCentre,
  CentreSlot,
  SlotBooking,
  QueueToken,
  ProcurementTransaction,
  CommodityPrice,
  GovernmentStock,
  PriceAlert,
  Complaint,
  AuditLog,
  NotificationItem,
  VendorRequest,
  AggregatedMarketStock,
} from '../types';

// ==============================================================================
// 1. DEMO USERS (All 7 Roles for 1-Click Evaluation)
// ==============================================================================
export const DEMO_PROFILES: UserProfile[] = [
  {
    id: 'user-farmer-01',
    role: 'farmer',
    fullName: 'Ramesh Kumar',
    mobileNumber: '+91 98290 12345',
    email: 'ramesh.farmer@smartmandi.gov.in',
    state: 'Rajasthan',
    district: 'Jaipur',
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'user-vendor-01',
    role: 'vendor',
    fullName: 'Rajeev Singhania (AgriCorp)',
    mobileNumber: '+91 98290 55443',
    email: 'procurement@agricorp.co.in',
    state: 'Rajasthan',
    district: 'Jaipur',
    createdAt: '2026-01-18T10:30:00Z',
  },
  {
    id: 'user-operator-01',
    role: 'centre_operator',
    fullName: 'Rajesh Sharma (Centre Sup.)',
    mobileNumber: '+91 94140 12345',
    email: 'operator.jaipur@smartmandi.gov.in',
    state: 'Rajasthan',
    district: 'Jaipur',
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'user-inspector-01',
    role: 'quality_inspector',
    fullName: 'Er. Alok Chouhan (Assayer)',
    mobileNumber: '+91 94140 88991',
    email: 'inspector.jaipur@smartmandi.gov.in',
    state: 'Rajasthan',
    district: 'Jaipur',
    createdAt: '2026-01-12T08:30:00Z',
  },
  {
    id: 'user-district-01',
    role: 'district_authority',
    fullName: 'Dr. Sunita Meena (DMO / Collector)',
    mobileNumber: '+91 94140 99000',
    email: 'dmo.jaipur@rajasthan.gov.in',
    state: 'Rajasthan',
    district: 'Jaipur',
    createdAt: '2026-01-05T09:00:00Z',
  },
  {
    id: 'user-ministry-01',
    role: 'ministry_admin',
    fullName: 'Sh. Arvind Varma (Joint Secretary)',
    mobileNumber: '+91 98110 33445',
    email: 'js.procurement@nic.in',
    state: 'Central Headquarters',
    district: 'New Delhi (Krishi Bhavan)',
    createdAt: '2026-01-01T10:00:00Z',
  },
  {
    id: 'user-superadmin-01',
    role: 'super_admin',
    fullName: 'NIC Cloud Admin',
    mobileNumber: '+91 98100 00001',
    email: 'superadmin@smartmandi.gov.in',
    state: 'Central',
    district: 'New Delhi',
    createdAt: '2026-01-01T00:00:00Z',
  },
];

// ==============================================================================
// 2. FARMERS DATA
// ==============================================================================
export const INITIAL_FARMERS: Farmer[] = [
  {
    id: 'farmer-01',
    profileId: 'user-farmer-01',
    farmerId: 'FMR-RJ-2026-1024',
    village: 'Bassi Rural',
    address: 'Khasra No. 142/3, Bassi Tehsil, Jaipur, Rajasthan - 303301',
    landAreaAcres: 4.5,
    landOwnershipStatus: 'Owned',
    preferredProcurementCentreId: 'centre-jaipur-01',
    aadhaarVerificationStatus: 'Verified',
    mobileVerified: true,
    bankVerified: true,
    landVerified: true,
    bankAccountMask: 'XXXX-XXXX-4819',
    ifscCode: 'SBIN0001234',
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'farmer-02',
    profileId: 'user-farmer-02',
    farmerId: 'FMR-RJ-2026-1088',
    village: 'Chaksu',
    address: 'Plot 18, Ward 4, Chaksu, Jaipur, Rajasthan - 303901',
    landAreaAcres: 6.2,
    landOwnershipStatus: 'Owned',
    preferredProcurementCentreId: 'centre-jaipur-01',
    aadhaarVerificationStatus: 'Verified',
    mobileVerified: true,
    bankVerified: true,
    landVerified: true,
    bankAccountMask: 'XXXX-XXXX-9921',
    ifscCode: 'PUNB0123400',
    createdAt: '2026-01-16T11:00:00Z',
  },
  {
    id: 'farmer-03',
    profileId: 'user-farmer-03',
    farmerId: 'FMR-PB-2026-2041',
    village: 'Sahnewal',
    address: 'VPO Sahnewal, GT Road, Ludhiana, Punjab - 141120',
    landAreaAcres: 9.0,
    landOwnershipStatus: 'Owned',
    preferredProcurementCentreId: 'centre-ludhiana-01',
    aadhaarVerificationStatus: 'Verified',
    mobileVerified: true,
    bankVerified: true,
    landVerified: true,
    bankAccountMask: 'XXXX-XXXX-3341',
    ifscCode: 'HDFC0000456',
    createdAt: '2026-01-12T14:00:00Z',
  },
];

// ==============================================================================
// 3. CROPS CATALOG (Govt MSP Rates in ₹/Quintal)
// ==============================================================================
export const INITIAL_CROPS: Crop[] = [
  {
    id: 'wheat',
    name: 'Wheat (Kalyan / Sharbati)',
    hindiName: 'गेहूं',
    category: 'Cereal',
    mspRate: 2425.0,
    unit: 'Quintal',
    qualityStandards: { maxMoisturePct: 12.0, maxForeignMatterPct: 0.75, minTestWeight: 76.0 },
  },
  {
    id: 'rice',
    name: 'Paddy / Rice (Common Grade)',
    hindiName: 'धान / चावल',
    category: 'Cereal',
    mspRate: 2300.0,
    unit: 'Quintal',
    qualityStandards: { maxMoisturePct: 17.0, maxForeignMatterPct: 1.0 },
  },
  {
    id: 'chana',
    name: 'Gram / Chana Dal',
    hindiName: 'चना',
    category: 'Pulse',
    mspRate: 5440.0,
    unit: 'Quintal',
    qualityStandards: { maxMoisturePct: 10.0, maxForeignMatterPct: 0.5 },
  },
  {
    id: 'mustard',
    name: 'Mustard Seed / Sarson',
    hindiName: 'सरसों',
    category: 'Oilseed',
    mspRate: 5650.0,
    unit: 'Quintal',
    qualityStandards: { minOilPct: 38.0, maxMoisturePct: 8.0 },
  },
  {
    id: 'onion',
    name: 'Onion (Red Nashik)',
    hindiName: 'प्याज',
    category: 'Vegetable',
    mspRate: 1850.0,
    unit: 'Quintal',
  },
  {
    id: 'potato',
    name: 'Potato (Kufri Jyoti)',
    hindiName: 'आलू',
    category: 'Vegetable',
    mspRate: 1450.0,
    unit: 'Quintal',
  },
  {
    id: 'tomato',
    name: 'Tomato (Hybrid Red)',
    hindiName: 'टमाटर',
    category: 'Vegetable',
    mspRate: 2100.0,
    unit: 'Quintal',
  },
];

// ==============================================================================
// 4. FARMER STOCK MODULE
// ==============================================================================
export const INITIAL_STOCKS: FarmerStock[] = [
  {
    id: 'stock-01',
    farmerId: 'farmer-01',
    cropId: 'wheat',
    cropName: 'Wheat (Kalyan / Sharbati)',
    variety: 'Sharbati HD-3086',
    cultivatedAreaAcres: 4.5,
    expectedProductionQuintals: 18.0,
    availableStockQuintals: 12.0,
    harvestDate: '2026-03-15',
    storageLocation: 'Pucca Farm Godown, Bassi',
    expectedProcurementQuintals: 12.0,
    qualityGrade: 'Grade A',
    status: 'Available for procurement',
    createdAt: '2026-03-16T10:00:00Z',
  },
  {
    id: 'stock-02',
    farmerId: 'farmer-01',
    cropId: 'mustard',
    cropName: 'Mustard Seed / Sarson',
    variety: 'Giriraj Mustard',
    cultivatedAreaAcres: 2.0,
    expectedProductionQuintals: 8.0,
    availableStockQuintals: 6.0,
    harvestDate: '2026-02-28',
    storageLocation: 'Pucca Farm Godown, Bassi',
    expectedProcurementQuintals: 6.0,
    qualityGrade: 'Grade A',
    status: 'Stored',
    createdAt: '2026-03-01T09:30:00Z',
  },
  {
    id: 'stock-03',
    farmerId: 'farmer-02',
    cropId: 'wheat',
    cropName: 'Wheat (Kalyan / Sharbati)',
    variety: 'Kalyansona',
    cultivatedAreaAcres: 6.2,
    expectedProductionQuintals: 26.0,
    availableStockQuintals: 20.0,
    harvestDate: '2026-03-18',
    storageLocation: 'Mandi Shed #4, Chaksu',
    expectedProcurementQuintals: 20.0,
    qualityGrade: 'Grade A',
    status: 'Available for procurement',
    createdAt: '2026-03-19T08:15:00Z',
  },
  {
    id: 'stock-04',
    farmerId: 'farmer-03',
    cropId: 'rice',
    cropName: 'Paddy / Rice (Common Grade)',
    variety: 'PR-126',
    cultivatedAreaAcres: 9.0,
    expectedProductionQuintals: 58.0,
    availableStockQuintals: 45.0,
    harvestDate: '2026-03-10',
    storageLocation: 'Sahnewal Silo',
    expectedProcurementQuintals: 45.0,
    qualityGrade: 'Grade A',
    status: 'Available for procurement',
    createdAt: '2026-03-11T12:00:00Z',
  },
];

// ==============================================================================
// 5. PROCUREMENT CENTRES
// ==============================================================================
export const INITIAL_CENTRES: ProcurementCentre[] = [
  {
    id: 'centre-jaipur-01',
    code: 'RJ-JPR-PC-01',
    name: 'Jaipur Central Mandi Procurement Centre',
    state: 'Rajasthan',
    district: 'Jaipur',
    mandiLocation: 'Muhana Mandi Complex, Gate No. 3, Sanganer, Jaipur',
    latitude: 26.8289,
    longitude: 75.7681,
    dailyFarmerCapacity: 300,
    activeBays: 6,
    operatingStatus: 'Operational',
    centreManagerName: 'Shri Rajesh Sharma',
    contactNumber: '+91 94140 12345',
    todayBookingsCount: 274,
    todayArrivedCount: 198,
    todayCompletedCount: 165,
    avgWaitMinutes: 38,
  },
  {
    id: 'centre-kota-02',
    code: 'RJ-KOT-PC-02',
    name: 'Kota Krishi Upaj Mandi Procurement Hub',
    state: 'Rajasthan',
    district: 'Kota',
    mandiLocation: 'Anantpura Industrial Area, Mandi Yard, Kota',
    latitude: 25.1384,
    longitude: 75.8457,
    dailyFarmerCapacity: 250,
    activeBays: 5,
    operatingStatus: 'Operational',
    centreManagerName: 'Smt. Anita Verma',
    contactNumber: '+91 94140 67890',
    todayBookingsCount: 210,
    todayArrivedCount: 160,
    todayCompletedCount: 140,
    avgWaitMinutes: 42,
  },
  {
    id: 'centre-ludhiana-01',
    code: 'PB-LDH-PC-01',
    name: 'Ludhiana Grain Procurement Centre',
    state: 'Punjab',
    district: 'Ludhiana',
    mandiLocation: 'Dana Mandi, Gill Road, Ludhiana',
    latitude: 30.892,
    longitude: 75.834,
    dailyFarmerCapacity: 450,
    activeBays: 8,
    operatingStatus: 'Operational',
    centreManagerName: 'S. Gurpreet Singh',
    contactNumber: '+91 98150 11223',
    todayBookingsCount: 412,
    todayArrivedCount: 345,
    todayCompletedCount: 310,
    avgWaitMinutes: 28,
  },
  {
    id: 'centre-hisar-01',
    code: 'HR-HSR-PC-01',
    name: 'Hisar Agricultural Mandi Complex',
    state: 'Haryana',
    district: 'Hisar',
    mandiLocation: 'New Grain Market, Delhi Road, Hisar',
    latitude: 29.1492,
    longitude: 75.7217,
    dailyFarmerCapacity: 300,
    activeBays: 6,
    operatingStatus: 'Operational',
    centreManagerName: 'Shri Vikram Punia',
    contactNumber: '+91 98120 44556',
    todayBookingsCount: 180,
    todayArrivedCount: 120,
    todayCompletedCount: 95,
    avgWaitMinutes: 30,
  },
  {
    id: 'centre-indore-01',
    code: 'MP-IND-PC-01',
    name: 'Indore Sanwer Road Krishi Mandi Hub',
    state: 'Madhya Pradesh',
    district: 'Indore',
    mandiLocation: 'Laxmibai Nagar Mandi, Sanwer Road, Indore',
    latitude: 22.7533,
    longitude: 75.8937,
    dailyFarmerCapacity: 350,
    activeBays: 7,
    operatingStatus: 'Operational',
    centreManagerName: 'Dr. Alok Chouhan',
    contactNumber: '+91 94250 88990',
    todayBookingsCount: 295,
    todayArrivedCount: 220,
    todayCompletedCount: 190,
    avgWaitMinutes: 35,
  },
];

// ==============================================================================
// 6. CENTRE TIME SLOTS (Today's Capacities)
// ==============================================================================
const todayDate = new Date().toISOString().split('T')[0];

export const INITIAL_SLOTS: CentreSlot[] = [
  { id: 'slot-01', centreId: 'centre-jaipur-01', slotDate: todayDate, timeWindow: '08:00 – 09:00 AM', capacity: 30, bookedCount: 30 },
  { id: 'slot-02', centreId: 'centre-jaipur-01', slotDate: todayDate, timeWindow: '09:00 – 10:00 AM', capacity: 30, bookedCount: 27 },
  { id: 'slot-03', centreId: 'centre-jaipur-01', slotDate: todayDate, timeWindow: '10:00 – 11:00 AM', capacity: 30, bookedCount: 23 },
  { id: 'slot-04', centreId: 'centre-jaipur-01', slotDate: todayDate, timeWindow: '11:00 – 12:00 PM', capacity: 30, bookedCount: 30 }, // FULL
  { id: 'slot-05', centreId: 'centre-jaipur-01', slotDate: todayDate, timeWindow: '12:00 – 01:00 PM', capacity: 30, bookedCount: 18 },
  { id: 'slot-06', centreId: 'centre-jaipur-01', slotDate: todayDate, timeWindow: '02:00 – 03:00 PM', capacity: 30, bookedCount: 15 },
  { id: 'slot-07', centreId: 'centre-jaipur-01', slotDate: todayDate, timeWindow: '03:00 – 04:00 PM', capacity: 30, bookedCount: 12 },
  { id: 'slot-08', centreId: 'centre-jaipur-01', slotDate: todayDate, timeWindow: '04:00 – 05:00 PM', capacity: 30, bookedCount: 8 },
];

// ==============================================================================
// 7. SLOT BOOKINGS
// ==============================================================================
export const INITIAL_BOOKINGS: SlotBooking[] = [
  {
    id: 'booking-ramesh-01',
    bookingReference: 'SB-2026-9812',
    farmerId: 'farmer-01',
    farmerName: 'Ramesh Kumar',
    centreId: 'centre-jaipur-01',
    centreName: 'Jaipur Central Mandi Procurement Centre',
    slotId: 'slot-03',
    cropId: 'wheat',
    cropName: 'Wheat (Kalyan / Sharbati)',
    slotDate: todayDate,
    timeWindow: '10:00 – 11:00 AM',
    declaredQuantityQuintals: 12.0,
    bookingStatus: 'Confirmed',
    tokenNumber: 'A-124',
    createdAt: '2026-03-18T16:00:00Z',
  },
  {
    id: 'booking-other-01',
    bookingReference: 'SB-2026-9790',
    farmerId: 'farmer-02',
    farmerName: 'Kailash Chand',
    centreId: 'centre-jaipur-01',
    centreName: 'Jaipur Central Mandi Procurement Centre',
    slotId: 'slot-02',
    cropId: 'wheat',
    cropName: 'Wheat (Kalyan / Sharbati)',
    slotDate: todayDate,
    timeWindow: '09:00 – 10:00 AM',
    declaredQuantityQuintals: 15.0,
    bookingStatus: 'Completed',
    tokenNumber: 'A-110',
    createdAt: '2026-03-18T14:30:00Z',
  },
];

// ==============================================================================
// 8. REAL-TIME QUEUE TOKENS (Live Mandi Queue State)
// ==============================================================================
export const INITIAL_TOKENS: QueueToken[] = [
  {
    id: 'token-110',
    tokenNumber: 'A-110',
    bookingId: 'booking-other-01',
    centreId: 'centre-jaipur-01',
    farmerId: 'farmer-02',
    farmerName: 'Kailash Chand',
    cropName: 'Wheat',
    quantityQuintals: 15.0,
    queueDate: todayDate,
    sequenceOrder: 110,
    status: 'COMPLETED',
    calledAt: '2026-03-19T09:15:00Z',
    completedAt: '2026-03-19T09:35:00Z',
    estimatedWaitMinutes: 0,
    createdAt: '2026-03-19T08:00:00Z',
  },
  {
    id: 'token-111',
    tokenNumber: 'A-111',
    bookingId: 'booking-111',
    centreId: 'centre-jaipur-01',
    farmerId: 'farmer-demo-03',
    farmerName: 'Sohan Lal',
    cropName: 'Wheat',
    quantityQuintals: 10.0,
    queueDate: todayDate,
    sequenceOrder: 111,
    status: 'WEIGHING',
    calledAt: '2026-03-19T09:36:00Z',
    estimatedWaitMinutes: 5,
    createdAt: '2026-03-19T08:05:00Z',
  },
  {
    id: 'token-112',
    tokenNumber: 'A-112',
    bookingId: 'booking-112',
    centreId: 'centre-jaipur-01',
    farmerId: 'farmer-demo-04',
    farmerName: 'Bhanwar Singh',
    cropName: 'Mustard',
    quantityQuintals: 8.0,
    queueDate: todayDate,
    sequenceOrder: 112,
    status: 'IN_VERIFICATION',
    calledAt: '2026-03-19T09:42:00Z',
    estimatedWaitMinutes: 10,
    createdAt: '2026-03-19T08:10:00Z',
  },
  {
    id: 'token-113',
    tokenNumber: 'A-113',
    bookingId: 'booking-113',
    centreId: 'centre-jaipur-01',
    farmerId: 'farmer-demo-05',
    farmerName: 'Ramprasad Yadav',
    cropName: 'Wheat',
    quantityQuintals: 14.5,
    queueDate: todayDate,
    sequenceOrder: 113,
    status: 'CALLED',
    calledAt: '2026-03-19T09:50:00Z',
    estimatedWaitMinutes: 15,
    createdAt: '2026-03-19T08:12:00Z',
  },
  // Ramesh Kumar is Token A-124
  {
    id: 'token-ramesh-124',
    tokenNumber: 'A-124',
    bookingId: 'booking-ramesh-01',
    centreId: 'centre-jaipur-01',
    farmerId: 'farmer-01',
    farmerName: 'Ramesh Kumar',
    cropName: 'Wheat',
    quantityQuintals: 12.0,
    queueDate: todayDate,
    sequenceOrder: 124,
    status: 'WAITING',
    estimatedWaitMinutes: 55, // 11 tokens ahead @ ~5 mins/token
    createdAt: '2026-03-19T08:30:00Z',
  },
];

// ==============================================================================
// 9. PROCUREMENT TRANSACTIONS (Complete Transparent Ledger)
// ==============================================================================
export const INITIAL_TRANSACTIONS: ProcurementTransaction[] = [
  {
    id: 'txn-demo-01',
    transactionId: 'TXN-2026-00124',
    bookingId: 'booking-ramesh-01',
    tokenId: 'token-ramesh-124',
    farmerId: 'farmer-01',
    farmerName: 'Ramesh Kumar',
    farmerCode: 'FMR-RJ-2026-1024',
    centreId: 'centre-jaipur-01',
    centreName: 'Jaipur Central Mandi Procurement Centre',
    cropId: 'wheat',
    cropName: 'Wheat (Sharbati HD-3086)',
    quantityQuintals: 12.0,
    mspRate: 2425.0,
    actualRate: 2425.0,
    grossAmount: 29100.0,
    
    // Transparent zero unauthorized fees guarantee
    authorisedCharges: 0.0,
    unauthorisedCharges: 0.0,
    netPayableAmount: 29100.0,
    
    qualityGrade: 'Grade A',
    moisturePercentage: 11.2,
    foreignMatterPercentage: 0.35,
    grossWeightKg: 13240.0,
    tareWeightKg: 12040.0,
    netWeightKg: 1200.0, // 12.0 quintals
    
    paymentStatus: 'Credited',
    digitalReceiptHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    verificationCode: 'AS-VFY-2026-99128',
    dbtReferenceUtr: 'PFMS2026031900984128',
    bankAccountMask: 'XXXX-XXXX-4819',
    timestamp: '2026-03-19T09:40:00Z',
  },
  {
    id: 'txn-demo-02',
    transactionId: 'TXN-2026-00123',
    bookingId: 'booking-other-01',
    tokenId: 'token-110',
    farmerId: 'farmer-02',
    farmerName: 'Kailash Chand',
    farmerCode: 'FMR-RJ-2026-1088',
    centreId: 'centre-jaipur-01',
    centreName: 'Jaipur Central Mandi Procurement Centre',
    cropId: 'wheat',
    cropName: 'Wheat (Kalyansona)',
    quantityQuintals: 15.0,
    mspRate: 2425.0,
    actualRate: 2425.0,
    grossAmount: 36375.0,
    authorisedCharges: 0.0,
    unauthorisedCharges: 0.0,
    netPayableAmount: 36375.0,
    qualityGrade: 'Grade A',
    moisturePercentage: 11.8,
    foreignMatterPercentage: 0.4,
    grossWeightKg: 14500.0,
    tareWeightKg: 13000.0,
    netWeightKg: 1500.0,
    paymentStatus: 'Processing',
    digitalReceiptHash: 'a7b8c94298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b123',
    verificationCode: 'AS-VFY-2026-99127',
    dbtReferenceUtr: 'PFMS2026031900984127',
    bankAccountMask: 'XXXX-XXXX-9921',
    timestamp: '2026-03-19T09:20:00Z',
  },
  {
    id: 'txn-demo-03',
    transactionId: 'TXN-2026-00098',
    bookingId: 'booking-ludhiana-01',
    tokenId: 'token-ldh-098',
    farmerId: 'farmer-03',
    farmerName: 'Harpreet Singh',
    farmerCode: 'FMR-PB-2026-2041',
    centreId: 'centre-ludhiana-01',
    centreName: 'Ludhiana Grain Procurement Centre',
    cropId: 'rice',
    cropName: 'Paddy / Rice (Common Grade)',
    quantityQuintals: 45.0,
    mspRate: 2300.0,
    actualRate: 2300.0,
    grossAmount: 103500.0,
    authorisedCharges: 0.0,
    unauthorisedCharges: 0.0,
    netPayableAmount: 103500.0,
    qualityGrade: 'Grade A',
    moisturePercentage: 15.2,
    foreignMatterPercentage: 0.8,
    grossWeightKg: 21500.0,
    tareWeightKg: 17000.0,
    netWeightKg: 4500.0,
    paymentStatus: 'Credited',
    digitalReceiptHash: 'c4d5e64298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b456',
    verificationCode: 'AS-VFY-2026-99098',
    dbtReferenceUtr: 'PFMS2026031800762190',
    bankAccountMask: 'XXXX-XXXX-3341',
    timestamp: '2026-03-18T14:15:00Z',
  },
];

// ==============================================================================
// 10. VERIFIED VENDORS & AGGREGATED STOCK
// ==============================================================================
export const INITIAL_VENDORS: Vendor[] = [
  {
    id: 'vendor-01',
    profileId: 'user-vendor-01',
    vendorCode: 'VND-2026-081',
    businessName: 'AgriCorp Agro Flour & Milling Ltd.',
    ownerName: 'Rajeev Singhania',
    businessType: 'Private Miller',
    gstNumberMask: '08XXXXX4312Z1',
    licenseNumber: 'FSSAI-LIC-1241800200091',
    verificationStatus: 'Verified',
    state: 'Rajasthan',
    district: 'Jaipur',
    commoditiesHandled: ['Wheat', 'Mustard', 'Chana'],
    storageCapacityMt: 1200.0,
    procurementCapacityMt: 450.0,
    contactPhone: '+91 98290 55443',
    contactEmail: 'procurement@agricorp.co.in',
    createdAt: '2026-01-18T10:30:00Z',
  },
  {
    id: 'vendor-02',
    profileId: 'user-vendor-02',
    vendorCode: 'VND-2026-094',
    businessName: 'Rajasthan Kisan Agro Processing Cooperative',
    ownerName: 'Vikram Choudhary',
    businessType: 'Cooperative',
    gstNumberMask: '08XXXXX9811A2',
    licenseNumber: 'COOP-REG-9810/2021',
    verificationStatus: 'Verified',
    state: 'Rajasthan',
    district: 'Kota',
    commoditiesHandled: ['Mustard', 'Soybean', 'Wheat'],
    storageCapacityMt: 800.0,
    procurementCapacityMt: 300.0,
    contactPhone: '+91 94140 33221',
    contactEmail: 'contact@rajkisancoop.org',
    createdAt: '2026-02-01T11:00:00Z',
  },
];

export const INITIAL_AGGREGATED_STOCKS: AggregatedMarketStock[] = [
  {
    cropName: 'Wheat',
    district: 'Jaipur',
    state: 'Rajasthan',
    totalAggregatedQuintals: 1250.0,
    participatingFarmersCount: 84,
    avgQuantityPerFarmer: 14.88,
    averageMspRate: 2425.0,
    marketRatePerQuintal: 2510.0,
  },
  {
    cropName: 'Mustard',
    district: 'Jaipur',
    state: 'Rajasthan',
    totalAggregatedQuintals: 620.0,
    participatingFarmersCount: 46,
    avgQuantityPerFarmer: 13.47,
    averageMspRate: 5650.0,
    marketRatePerQuintal: 5820.0,
  },
  {
    cropName: 'Wheat',
    district: 'Kota',
    state: 'Rajasthan',
    totalAggregatedQuintals: 2180.0,
    participatingFarmersCount: 128,
    avgQuantityPerFarmer: 17.03,
    averageMspRate: 2425.0,
    marketRatePerQuintal: 2480.0,
  },
  {
    cropName: 'Rice (Paddy)',
    district: 'Ludhiana',
    state: 'Punjab',
    totalAggregatedQuintals: 4800.0,
    participatingFarmersCount: 165,
    avgQuantityPerFarmer: 29.09,
    averageMspRate: 2300.0,
    marketRatePerQuintal: 2380.0,
  },
  {
    cropName: 'Chana (Gram)',
    district: 'Indore',
    state: 'Madhya Pradesh',
    totalAggregatedQuintals: 940.0,
    participatingFarmersCount: 62,
    avgQuantityPerFarmer: 15.16,
    averageMspRate: 5440.0,
    marketRatePerQuintal: 5600.0,
  },
];

// ==============================================================================
// 11. COMMODITY PRICES (Department of Consumer Affairs - DoCA Module)
// ==============================================================================
export const INITIAL_PRICES: CommodityPrice[] = [
  {
    id: 'price-01',
    commodity: 'Wheat',
    state: 'Rajasthan',
    district: 'Jaipur',
    mandiName: 'Muhana Mandi',
    farmGatePrice: 24.25,
    wholesalePrice: 27.5,
    retailPrice: 32.0,
    spread: 7.75,
    dailyArrivalQuintals: 4200.0,
    sourceAgency: 'DoCA / Agmarknet Demo Feed',
    reportedDate: todayDate,
    change24h: 2.7,
    change7d: 8.4,
    change30d: 12.2,
  },
  {
    id: 'price-02',
    commodity: 'Wheat',
    state: 'Punjab',
    district: 'Ludhiana',
    mandiName: 'Dana Mandi',
    farmGatePrice: 24.25,
    wholesalePrice: 26.8,
    retailPrice: 31.5,
    spread: 7.25,
    dailyArrivalQuintals: 8900.0,
    sourceAgency: 'DoCA / Agmarknet Demo Feed',
    reportedDate: todayDate,
    change24h: 0.5,
    change7d: 1.8,
    change30d: 4.1,
  },
  {
    id: 'price-03',
    commodity: 'Rice',
    state: 'Punjab',
    district: 'Ludhiana',
    mandiName: 'Dana Mandi',
    farmGatePrice: 23.0,
    wholesalePrice: 28.5,
    retailPrice: 36.0,
    spread: 13.0,
    dailyArrivalQuintals: 7200.0,
    sourceAgency: 'DoCA / Agmarknet Demo Feed',
    reportedDate: todayDate,
    change24h: 0.8,
    change7d: 2.1,
    change30d: 5.5,
  },
  {
    id: 'price-04',
    commodity: 'Tomato',
    state: 'Rajasthan',
    district: 'Jaipur',
    mandiName: 'Muhana Mandi',
    farmGatePrice: 28.0,
    wholesalePrice: 38.0,
    retailPrice: 52.0,
    spread: 24.0, // Significant spread spike!
    dailyArrivalQuintals: 1850.0,
    sourceAgency: 'DoCA / Agmarknet Demo Feed',
    reportedDate: todayDate,
    change24h: 14.2,
    change7d: 36.8,
    change30d: 48.0,
  },
  {
    id: 'price-05',
    commodity: 'Onion',
    state: 'Maharashtra',
    district: 'Nashik',
    mandiName: 'Lasalgaon Mandi',
    farmGatePrice: 18.5,
    wholesalePrice: 24.0,
    retailPrice: 35.0,
    spread: 16.5,
    dailyArrivalQuintals: 12500.0,
    sourceAgency: 'DoCA / Agmarknet Demo Feed',
    reportedDate: todayDate,
    change24h: -1.2,
    change7d: -3.5,
    change30d: 8.0,
  },
  {
    id: 'price-06',
    commodity: 'Onion',
    state: 'Rajasthan',
    district: 'Jaipur',
    mandiName: 'Muhana Mandi',
    farmGatePrice: 21.0,
    wholesalePrice: 27.5,
    retailPrice: 38.0,
    spread: 17.0,
    dailyArrivalQuintals: 3100.0,
    sourceAgency: 'DoCA / Agmarknet Demo Feed',
    reportedDate: todayDate,
    change24h: 3.4,
    change7d: 11.2,
    change30d: 18.7,
  },
  {
    id: 'price-07',
    commodity: 'Potato',
    state: 'Uttar Pradesh',
    district: 'Agra',
    mandiName: 'Fatehabad Mandi',
    farmGatePrice: 14.5,
    wholesalePrice: 18.2,
    retailPrice: 24.0,
    spread: 9.5,
    dailyArrivalQuintals: 15000.0,
    sourceAgency: 'DoCA / Agmarknet Demo Feed',
    reportedDate: todayDate,
    change24h: 0.0,
    change7d: 1.2,
    change30d: 3.4,
  },
  {
    id: 'price-08',
    commodity: 'Chana',
    state: 'Madhya Pradesh',
    district: 'Indore',
    mandiName: 'Laxmibai Nagar Mandi',
    farmGatePrice: 54.4,
    wholesalePrice: 62.0,
    retailPrice: 74.0,
    spread: 19.6,
    dailyArrivalQuintals: 3800.0,
    sourceAgency: 'DoCA / Agmarknet Demo Feed',
    reportedDate: todayDate,
    change24h: 1.1,
    change7d: 4.2,
    change30d: 7.9,
  },
  {
    id: 'price-09',
    commodity: 'Mustard',
    state: 'Rajasthan',
    district: 'Jaipur',
    mandiName: 'Muhana Mandi',
    farmGatePrice: 56.5,
    wholesalePrice: 64.0,
    retailPrice: 135.0, // Oil per L approx
    spread: 78.5,
    dailyArrivalQuintals: 2900.0,
    sourceAgency: 'DoCA / Agmarknet Demo Feed',
    reportedDate: todayDate,
    change24h: 0.5,
    change7d: 2.0,
    change30d: 5.1,
  },
];

// ==============================================================================
// 12. GOVERNMENT BUFFER STOCK MANAGEMENT
// ==============================================================================
export const INITIAL_GOV_STOCKS: GovernmentStock[] = [
  {
    id: 'stock-cwc-01',
    commodity: 'Wheat',
    warehouseName: 'Central Warehouse Corporation (CWC) Sanganer',
    state: 'Rajasthan',
    district: 'Jaipur',
    currentStockMt: 10500.0,
    capacityMt: 15000.0,
    utilizationPct: 70.0,
    averageStockAgeDays: 45,
    conditionRating: 'Optimal',
    updatedAt: '2026-03-19T06:00:00Z',
  },
  {
    id: 'stock-fci-02',
    commodity: 'Wheat',
    warehouseName: 'Food Corporation of India (FCI) Silo Complex Ludhiana',
    state: 'Punjab',
    district: 'Ludhiana',
    currentStockMt: 42000.0,
    capacityMt: 50000.0,
    utilizationPct: 84.0,
    averageStockAgeDays: 62,
    conditionRating: 'Optimal',
    updatedAt: '2026-03-19T06:00:00Z',
  },
  {
    id: 'stock-swc-03',
    commodity: 'Rice',
    warehouseName: 'Haryana SWC Godown Karnal',
    state: 'Haryana',
    district: 'Karnal',
    currentStockMt: 24500.0,
    capacityMt: 30000.0,
    utilizationPct: 81.67,
    averageStockAgeDays: 75,
    conditionRating: 'Optimal',
    updatedAt: '2026-03-19T06:00:00Z',
  },
  {
    id: 'stock-nafed-04',
    commodity: 'Chana',
    warehouseName: 'NAFED Buffer Depot Dewas',
    state: 'Madhya Pradesh',
    district: 'Dewas',
    currentStockMt: 8200.0,
    capacityMt: 12000.0,
    utilizationPct: 68.33,
    averageStockAgeDays: 90,
    conditionRating: 'Fair',
    updatedAt: '2026-03-18T18:00:00Z',
  },
  {
    id: 'stock-raj-05',
    commodity: 'Mustard',
    warehouseName: 'Rajasthan State Seed Corp Warehouse Kota',
    state: 'Rajasthan',
    district: 'Kota',
    currentStockMt: 6400.0,
    capacityMt: 8000.0,
    utilizationPct: 80.0,
    averageStockAgeDays: 35,
    conditionRating: 'Optimal',
    updatedAt: '2026-03-19T06:30:00Z',
  },
];

// ==============================================================================
// 13. ANOMALY & EARLY WARNING ALERTS
// ==============================================================================
export const INITIAL_ALERTS: PriceAlert[] = [
  {
    id: 'alert-01',
    commodity: 'Tomato',
    district: 'Jaipur',
    alertType: 'Price Spike',
    severity: 'High Alert',
    currentPrice: 52.0,
    benchmarkPrice: 38.0,
    percentageDeviation: 36.84,
    anomalyReason: 'Arrivals dropped 38% in Western corridors while retail markup widened to ₹24/kg. Potential supply squeeze detected.',
    status: 'Flagged for Review',
    createdAt: '2026-03-19T07:15:00Z',
  },
  {
    id: 'alert-02',
    commodity: 'Wheat',
    district: 'Jaipur',
    alertType: 'Abnormal Price Spread',
    severity: 'Medium',
    currentPrice: 32.0,
    benchmarkPrice: 28.5,
    percentageDeviation: 12.28,
    anomalyReason: 'Farm-to-retail spread reached ₹7.75/kg vs historical ₹6.20/kg benchmark. Intermediary margin expansion flagged.',
    status: 'Flagged for Review',
    createdAt: '2026-03-18T16:45:00Z',
  },
  {
    id: 'alert-03',
    commodity: 'Onion',
    district: 'Jaipur',
    alertType: 'Supply Stress Watch',
    severity: 'Medium',
    currentPrice: 38.0,
    benchmarkPrice: 32.0,
    percentageDeviation: 18.75,
    anomalyReason: 'Arrivals: ↓ 22%, Stock: ↓ 15%, Price: ↑ 18.7%. Potential supply bottleneck detected across Eastern Rajasthan godowns.',
    status: 'Investigating',
    createdAt: '2026-03-18T11:20:00Z',
  },
];

// ==============================================================================
// 14. GRIEVANCES & CITIZEN COMPLAINTS
// ==============================================================================
export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'cmp-01',
    complaintCode: 'CMP-2026-4410',
    farmerId: 'farmer-01',
    farmerName: 'Ramesh Kumar',
    transactionId: 'TXN-2026-00124',
    category: 'Delayed Payment',
    description: 'Procurement completed at 09:40 AM; request confirmation of DBT batch release via PFMS gateway.',
    status: 'Resolved',
    assignedOfficer: 'Dr. Sunita Meena (DMO Jaipur)',
    resolutionNotes: 'DBT Batch credited under UTR PFMS2026031900984128. Account credited successfully.',
    createdAt: '2026-03-19T10:15:00Z',
    resolvedAt: '2026-03-19T10:45:00Z',
  },
  {
    id: 'cmp-02',
    complaintCode: 'CMP-2026-4402',
    farmerId: 'farmer-02',
    farmerName: 'Kailash Chand',
    category: 'Extra Charges Demanded',
    description: 'Private handling agent at Gate 2 requested ₹150 for unauthorized unloading slip.',
    status: 'Investigation',
    assignedOfficer: 'Shri Rajesh Sharma (Centre Manager)',
    resolutionNotes: 'Security review underway. Unloading fee strictly prohibited under Mandi Act Section 14.',
    createdAt: '2026-03-18T14:30:00Z',
  },
  {
    id: 'cmp-03',
    complaintCode: 'CMP-2026-4395',
    farmerId: 'farmer-03',
    farmerName: 'Harpreet Singh',
    category: 'Quality Dispute',
    description: 'Initial moisture reading showed 17.5%; requested secondary moisture test using calibrated digital sensor.',
    status: 'Resolved',
    assignedOfficer: 'Er. Alok Chouhan (Assayer)',
    resolutionNotes: 'Re-tested on Master Grain Moisture meter; verified at 15.2% (Grade A). Procurement completed.',
    createdAt: '2026-03-18T12:00:00Z',
    resolvedAt: '2026-03-18T13:10:00Z',
  },
];

// ==============================================================================
// 15. SENSITIVE ACTION AUDIT LOGS
// ==============================================================================
export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-01',
    userId: 'user-operator-01',
    userName: 'Rajesh Sharma',
    userRole: 'centre_operator',
    actionType: 'QUEUE_ADVANCED',
    recordId: 'A-110',
    tableName: 'queue_tokens',
    oldValue: 'Status: WAITING',
    newValue: 'Status: COMPLETED (Procurement Finished)',
    ipAddress: '10.24.8.12 (Jaipur Mandi Intranet)',
    createdAt: '2026-03-19T09:35:10Z',
  },
  {
    id: 'log-02',
    userId: 'user-operator-01',
    userName: 'Rajesh Sharma',
    userRole: 'centre_operator',
    actionType: 'PROCUREMENT_COMPLETED',
    recordId: 'TXN-2026-00124',
    tableName: 'procurement_transactions',
    oldValue: 'Net Weight: Null',
    newValue: 'Net: 12.0 Quintals, MSP: ₹2,425, Gross: ₹29,100, Deductions: ₹0',
    ipAddress: '10.24.8.12 (Jaipur Mandi Intranet)',
    createdAt: '2026-03-19T09:40:02Z',
  },
  {
    id: 'log-03',
    userId: 'user-ministry-01',
    userName: 'Sh. Arvind Varma',
    userRole: 'ministry_admin',
    actionType: 'PRICE_UPDATED',
    recordId: 'WHEAT-MSP-2026',
    tableName: 'crops',
    oldValue: 'MSP: ₹2,275/Qtl',
    newValue: 'MSP: ₹2,425/Qtl (Rabi Season Gazette Notification)',
    ipAddress: '14.139.60.25 (Krishi Bhavan HQ)',
    createdAt: '2026-03-15T11:00:00Z',
  },
  {
    id: 'log-04',
    userId: 'user-district-01',
    userName: 'Dr. Sunita Meena',
    userRole: 'district_authority',
    actionType: 'COMPLAINT_RESOLVED',
    recordId: 'CMP-2026-4410',
    tableName: 'complaints',
    oldValue: 'Status: Submitted',
    newValue: 'Status: Resolved (DBT Released under UTR PFMS2026031900984128)',
    ipAddress: '10.20.1.4 (District Collectorate Jaipur)',
    createdAt: '2026-03-19T10:45:15Z',
  },
  {
    id: 'log-05',
    userId: 'user-superadmin-01',
    userName: 'NIC Cloud Admin',
    userRole: 'super_admin',
    actionType: 'VENDOR_VERIFIED',
    recordId: 'VND-2026-081',
    tableName: 'vendors',
    oldValue: 'Verification: Under Review',
    newValue: 'Verification: Verified (FSSAI & Mandi License Validated)',
    ipAddress: '164.100.128.5 (NIC National Gateway)',
    createdAt: '2026-03-10T14:20:00Z',
  },
];

// ==============================================================================
// 16. NOTIFICATIONS (In-App & Simulated SMS)
// ==============================================================================
export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-01',
    userId: 'user-farmer-01',
    title: 'Payment Credited Successfully',
    message: 'Your payment of ₹29,100 for 12.0 Quintals Wheat has been credited to your bank account (A/C: XXXX-4819). UTR: PFMS2026031900984128.',
    category: 'Payment',
    read: false,
    deliveryStatus: 'SMS Mock Sent',
    createdAt: '2026-03-19T10:05:00Z',
  },
  {
    id: 'notif-02',
    userId: 'user-farmer-01',
    title: 'Queue Alert: Token A-124 Approaching',
    message: 'Currently Serving: A-113. Only 10 farmers ahead at Jaipur Central Mandi. Please report to Bay 3.',
    category: 'Queue',
    read: true,
    deliveryStatus: 'SMS Mock Sent',
    createdAt: '2026-03-19T09:50:00Z',
  },
  {
    id: 'notif-03',
    userId: 'user-farmer-01',
    title: 'Slot Booking Confirmed',
    message: 'Your slot on today (10:00 – 11:00 AM) at Jaipur Central Mandi is confirmed. Token No: A-124.',
    category: 'Slot',
    read: true,
    deliveryStatus: 'SMS Mock Sent',
    createdAt: '2026-03-18T16:00:00Z',
  },
  {
    id: 'notif-04',
    userId: 'user-vendor-01',
    title: 'New Aggregated Wheat Available',
    message: '1,250 Quintals of Grade A Wheat aggregated in Jaipur district across 84 verified farmers.',
    category: 'Price',
    read: false,
    deliveryStatus: 'In-App Sent',
    createdAt: '2026-03-19T08:00:00Z',
  },
];

// ==============================================================================
// 17. VENDOR PROCUREMENT INTEREST REQUESTS
// ==============================================================================
export const INITIAL_VENDOR_REQUESTS: VendorRequest[] = [
  {
    id: 'req-01',
    vendorId: 'vendor-01',
    vendorName: 'AgriCorp Agro Flour & Milling Ltd.',
    cropId: 'wheat',
    cropName: 'Wheat (Grade A)',
    district: 'Jaipur',
    targetQuantityQuintals: 300.0,
    offeredRateQuintal: 2520.0,
    status: 'Active',
    createdAt: '2026-03-19T08:30:00Z',
  },
  {
    id: 'req-02',
    vendorId: 'vendor-02',
    vendorName: 'Rajasthan Kisan Agro Processing Cooperative',
    cropId: 'mustard',
    cropName: 'Mustard Seed',
    district: 'Kota',
    targetQuantityQuintals: 200.0,
    offeredRateQuintal: 5800.0,
    status: 'Active',
    createdAt: '2026-03-18T15:00:00Z',
  },
];
